In [1]:
import pandas as pd
import numpy as np
from collections import Counter

In [2]:
np.random.seed(16)

In [3]:
def euclidian_distance(query,X):
        difference = np.array(X) - np.array(query)
        sqrd_diff = np.square(difference)
        sum_sqrd_diff = np.sum(sqrd_diff, axis = 1)
        distance = np.sqrt(sum_sqrd_diff)
        return distance

In [4]:
df = pd.read_csv("fruit_data_with_colors.txt",delimiter = "\t")
df = df.drop(['fruit_label', 'fruit_subtype', 'fruit_name'], axis=1)
X = np.array(df)
X

array([[1.92e+02, 8.40e+00, 7.30e+00, 5.50e-01],
       [1.80e+02, 8.00e+00, 6.80e+00, 5.90e-01],
       [1.76e+02, 7.40e+00, 7.20e+00, 6.00e-01],
       [8.60e+01, 6.20e+00, 4.70e+00, 8.00e-01],
       [8.40e+01, 6.00e+00, 4.60e+00, 7.90e-01],
       [8.00e+01, 5.80e+00, 4.30e+00, 7.70e-01],
       [8.00e+01, 5.90e+00, 4.30e+00, 8.10e-01],
       [7.60e+01, 5.80e+00, 4.00e+00, 8.10e-01],
       [1.78e+02, 7.10e+00, 7.80e+00, 9.20e-01],
       [1.72e+02, 7.40e+00, 7.00e+00, 8.90e-01],
       [1.66e+02, 6.90e+00, 7.30e+00, 9.30e-01],
       [1.72e+02, 7.10e+00, 7.60e+00, 9.20e-01],
       [1.54e+02, 7.00e+00, 7.10e+00, 8.80e-01],
       [1.64e+02, 7.30e+00, 7.70e+00, 7.00e-01],
       [1.52e+02, 7.60e+00, 7.30e+00, 6.90e-01],
       [1.56e+02, 7.70e+00, 7.10e+00, 6.90e-01],
       [1.00e+03, 7.60e+00, 7.50e+00, 6.70e-01],
       [1.68e+02, 7.50e+00, 7.60e+00, 7.30e-01],
       [1.62e+02, 7.50e+00, 7.10e+00, 8.30e-01],
       [1.62e+02, 7.40e+00, 7.20e+00, 8.50e-01],
       [1.60e+02, 7.

In [5]:
K = 4

In [6]:
centroidIndex = np.random.randint(0,58,(K,))
centroids = X[centroidIndex]

In [7]:
print(centroidIndex)

[41 46 57  5]


In [8]:
print(centroids)

[[180.     7.6    8.2    0.79]
 [216.     7.3   10.2    0.71]
 [152.     6.5    8.5    0.72]
 [ 80.     5.8    4.3    0.77]]


In [9]:
X_ = np.delete(X,centroidIndex, axis = 0)

clusters = [[],[],[],[]]
clusters[0].append(centroids[0])
clusters[1].append(centroids[1])
clusters[2].append(centroids[2])
clusters[3].append(centroids[3])

In [10]:
for i in range(10):
    print('iteration:',i+1, end = '\n')
    clusters = [[],[],[],[]]

    for x in X:
        id = np.argmin(euclidian_distance(x,centroids))
        clusters[id].append(x)

    c = np.array(clusters, dtype = object)

    for x in range(4):
        centroids[x] = np.mean(c[x], axis = 0)
        print(centroids[x])

    print()

iteration: 1
[179.6          7.43333333   8.14         0.76      ]
[3.65444444e+03 8.04444444e+00 8.96666667e+00 7.45555556e-01]
[144.46666667   6.87         7.64333333   0.76433333]
[81.2    5.94   4.38   0.796]

iteration: 2
[236.48     7.652    8.4      0.7532]
[3.0e+04 7.1e+00 7.5e+00 7.8e-01]
[143.07142857   6.84285714   7.66428571   0.76535714]
[81.2    5.94   4.38   0.796]

iteration: 3
[305.16666667   7.975        9.05         0.72      ]
[3.0e+04 7.1e+00 7.5e+00 7.8e-01]
[152.58536585   7.00487805   7.70731707   0.77121951]
[81.2    5.94   4.38   0.796]

iteration: 4
[515.       8.85     8.825    0.7275]
[3.0e+04 7.1e+00 7.5e+00 7.8e-01]
[164.31111111   7.18222222   7.94444444   0.766     ]
[96.66666667  6.          5.96666667  0.76222222]

iteration: 5
[515.       8.85     8.825    0.7275]
[3.0e+04 7.1e+00 7.5e+00 7.8e-01]
[168.48780488   7.29756098   7.92195122   0.77073171]
[104.30769231   6.           6.64615385   0.74846154]

iteration: 6
[515.       8.85     8.825    0.7