In [15]:
import pandas as pd
import numpy as np
from collections import Counter

In [16]:
df = pd.read_csv("fruit_data_with_colors.txt",delimiter = "\t")

In [17]:
df

fruit_label fruit_name     fruit_subtype   mass  width  height  \
0             1      apple      granny_smith    192    8.4     7.3   
1             1      apple      granny_smith    180    8.0     6.8   
2             1      apple      granny_smith    176    7.4     7.2   
3             2   mandarin          mandarin     86    6.2     4.7   
4             2   mandarin          mandarin     84    6.0     4.6   
5             2   mandarin          mandarin     80    5.8     4.3   
6             2   mandarin          mandarin     80    5.9     4.3   
7             2   mandarin          mandarin     76    5.8     4.0   
8             1      apple          braeburn    178    7.1     7.8   
9             1      apple          braeburn    172    7.4     7.0   
10            1      apple          braeburn    166    6.9     7.3   
11            1      apple          braeburn    172    7.1     7.6   
12            1      apple          braeburn    154    7.0     7.1   
13            1      apple  golden_delicious    164    7.3     7.7   
14            1      apple  golden_delicious    152    7.6     7.3   
15            1      apple  golden_delicious    156    7.7     7.1   
16            1      apple  golden_delicious   1000    7.6     7.5   
17            1      apple  golden_delicious    168    7.5     7.6   
18            1      apple       cripps_pink    162    7.5     7.1   
19            1      apple       cripps_pink    162    7.4     7.2   
20            1      apple       cripps_pink    160    7.5     7.5   
21            1      apple       cripps_pink    156    7.4     7.4   
22            1      apple       cripps_pink    140    7.3     7.1   
23            1      apple       cripps_pink    170    7.6     7.9   
24            3     orange     spanish_jumbo    342    9.0     9.4   
25            3     orange     spanish_jumbo    356    9.2     9.2   
26            3     orange     spanish_jumbo    362    9.6     9.2   
27            3     orange  selected_seconds    204    7.5     9.2   
28            3     orange  selected_seconds    140    6.7     7.1   
29            3     orange  selected_seconds    160    7.0     7.4   
30            3     orange  selected_seconds    158    7.1     7.5   
31            3     orange  selected_seconds    210    7.8     8.0   
32            3     orange  selected_seconds    164    7.2     7.0   
33            3     orange      turkey_navel    190    7.5     8.1   
34            3     orange      turkey_navel    142    7.6     7.8   
35            3     orange      turkey_navel    150    7.1     7.9   
36            3     orange      turkey_navel    160    7.1     7.6   
37            3     orange      turkey_navel    154    7.3     7.3   
38            3     orange      turkey_navel    158    7.2     7.8   
39            3     orange      turkey_navel    154    7.3     7.5   
40            3     orange      turkey_navel  30000    7.1     7.5   
41            3     orange      turkey_navel    180    7.6     8.2   
42            3     orange      turkey_navel    154    7.2     7.2   
43            4      lemon    spanish_belsan    194    7.2    10.3   
44            4      lemon    spanish_belsan    200    7.3    10.5   
45            4      lemon    spanish_belsan    186    7.2     9.2   
46            4      lemon    spanish_belsan    216    7.3    10.2   
47            4      lemon    spanish_belsan    196    7.3     9.7   
48            4      lemon    spanish_belsan    174    7.3    10.1   
49            4      lemon           unknown    132    5.8     8.7   
50            4      lemon           unknown    130    6.0     8.2   
51            4      lemon           unknown    116    6.0     7.5   
52            4      lemon           unknown    118    5.9     8.0   
53            4      lemon           unknown    120    6.0     8.4   
54            4      lemon           unknown    116    6.1     8.5   
55            4      lemon           unknown    116    6.3     7.7   
56            

In [18]:
X = df[["mass","width","height"]]

In [19]:
Y = df["fruit_label"]

In [20]:
trainX = np.array(X[:50])
trainY = np.array(Y[:50])
testX = np.array(X[50:])
testY = np.array(Y[50:])


In [21]:
class KNN:
    def __init__(self,k = 1):
        self.k = k
        
    def euclidian_distance(self,query,X):
        difference = np.array(X) - np.array(query)
        sqrd_diff = np.square(difference)
        sum_sqrd_diff = np.sum(sqrd_diff, axis = 1)
        distance = np.sqrt(sum_sqrd_diff)
        return distance
    
    def nearest_neighbours(self,distance):
        return np.argsort(distance)[:self.k]
    
    def predict(self,query,trainX,trainY):
        ed = self.euclidian_distance(query,trainX)
        nn = self.nearest_neighbours(ed)
        labels_nn = list(trainY[nn])
        return max(labels_nn, key = labels_nn.count) 
    

In [22]:
classifier = KNN(1)

In [31]:
dist=[classifier.euclidian_distance(x,trainX) for x in testX]
dist

[array([6.20529613e+01, 5.00595645e+01, 4.60321627e+01, 4.41394381e+01,
        4.61406545e+01, 5.01522681e+01, 5.01519691e+01, 5.41634563e+01,
        4.80142687e+01, 4.20404567e+01, 3.60224930e+01, 4.20186863e+01,
        2.40459976e+01, 3.40285175e+01, 2.20764580e+01, 2.60787270e+01,
        8.70001753e+02, 3.80343266e+01, 3.20540169e+01, 3.20462166e+01,
        3.00456320e+01, 2.60499520e+01, 1.01439637e+01, 4.00331113e+01,
        2.12024621e+02, 2.26024866e+02, 2.32030084e+02, 7.40219562e+01,
        1.00846418e+01, 3.00273209e+01, 2.80303407e+01, 8.00204974e+01,
        3.40423266e+01, 6.00188304e+01, 1.21128031e+01, 2.00324736e+01,
        3.00261553e+01, 2.40520269e+01, 2.80285569e+01, 2.40453738e+01,
        2.98700000e+04, 5.00255934e+01, 2.40507796e+01, 6.40456868e+01,
        7.00498394e+01, 5.60217815e+01, 8.60330750e+01, 6.60298417e+01,
        4.40601861e+01, 2.07123152e+00]),
 array([7.60381483e+01, 6.40350685e+01, 6.00170809e+01, 3.01310471e+01,
        3.21311375e+01

In [32]:
predictions = [classifier.predict(x,trainX,trainY) for x in testX]

In [33]:
predictions

[4, 4, 4, 4, 4, 4, 4, 1, 4]

In [34]:
testY

array([4, 4, 4, 4, 4, 4, 4, 4, 4], dtype=int64)

In [35]:
from sklearn.metrics import accuracy_score
a = accuracy_score(testY, predictions)
a

0.8888888888888888

In [13]:
from sklearn.metrics import confusion_matrix
b = confusion_matrix(testY, predictions)
b

array([[0, 0],
       [1, 8]], dtype=int64)