In [1]:
import pandas as pd
import numpy as np

In [2]:
# Q1

In [3]:
df = pd.DataFrame(np.array([[0,0,0],[0,1,1],[1,0,1],[1,1,0]]), columns=['x1','x2','label'])

In [4]:
df

x1  x2  label
0   0   0      0
1   0   1      1
2   1   0      1
3   1   1      0

In [29]:
W = np.random.rand(2,1)
W.shape

(2, 1)

In [15]:
b = np.random.rand()
b

0.04860826177879396

In [16]:
x = np.array(df[['x1','x2']])
y = np.array(df['label'])
x=x.T
x, y

(array([[0, 0, 1, 1],
        [0, 1, 0, 1]]),
 array([0, 1, 1, 0]))

In [17]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))

from sklearn.metrics import log_loss

In [63]:
for i in range (50):
    Z =np.dot(W.T,x)+b
    A = sigmoid(Z)
    A = np.where(A < 0.5, 0, 1)
    A = A.squeeze()
    
    
    J = log_loss(y,A)
    print(J)
    
    dz = A - y
    dz = np.expand_dims(dz, axis = 0)
    dw =  np.dot(x,dz.T)/x.shape[0]
    db = np.sum(dz,axis =1)/x.shape[0]
    alpha = 0.000001
    W = W - alpha * dw
    b = b - alpha *db

25.90428219554056
17.26958809681289
25.90428219554056
17.26958809681289
25.90428219554056
17.26958809681289
25.90428219554056
17.26958809681289
25.90428219554056
17.26958809681289
25.90428219554056
17.26958809681289
25.90428219554056
17.26958809681289
25.90428219554056
17.26958809681289
25.90428219554056
17.26958809681289
25.90428219554056
17.26958809681289
25.90428219554056
17.26958809681289
25.90428219554056
17.26958809681289
25.90428219554056
17.26958809681289
25.90428219554056
17.26958809681289
25.90428219554056
17.26958809681289
25.90428219554056
17.26958809681289
25.90428219554056
17.26958809681289
25.90428219554056
17.26958809681289
25.90428219554056
8.63489399808522
25.90428219554056
25.90428219554056
8.63489399808522
25.90428219554056
25.90428219554056
8.63489399808522
25.90428219554056
25.90428219554056
8.63489399808522
25.90428219554056
25.90428219554056
8.63489399808522


In [64]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y, A)

array([[1, 1],
       [0, 2]], dtype=int64)

In [65]:
A  #Predictions

array([0, 1, 1, 1])

In [62]:
y  #actual label

array([0, 1, 1, 0])